// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: chat_db.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatDBService_AuthenticateUser_FullMethodName = "/chatdb.ChatDBService/AuthenticateUser"
	ChatDBService_RegisterUser_FullMethodName     = "/chatdb.ChatDBService/RegisterUser"
	ChatDBService_IssueToken_FullMethodName       = "/chatdb.ChatDBService/IssueToken"
	ChatDBService_VerifyToken_FullMethodName      = "/chatdb.ChatDBService/VerifyToken"
	ChatDBService_SetSessionState_FullMethodName  = "/chatdb.ChatDBService/SetSessionState"
	ChatDBService_PublishChat_FullMethodName      = "/chatdb.ChatDBService/PublishChat"
	ChatDBService_GetChatHistory_FullMethodName   = "/chatdb.ChatDBService/GetChatHistory"
)

// ChatDBServiceClient is the client API for ChatDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --- gRPC DB 서비스 정의 ---
type ChatDBServiceClient interface {
	AuthenticateUser(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	RegisterUser(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error)
	VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error)
	SetSessionState(ctx context.Context, in *SessionStateRequest, opts ...grpc.CallOption) (*SessionStateResponse, error)
	PublishChat(ctx context.Context, in *ChatPublishRequest, opts ...grpc.CallOption) (*ChatPublishResponse, error)
	GetChatHistory(ctx context.Context, in *ChatHistoryRequest, opts ...grpc.CallOption) (*ChatHistoryResponse, error)
}

type chatDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatDBServiceClient(cc grpc.ClientConnInterface) ChatDBServiceClient {
	return &chatDBServiceClient{cc}
}

func (c *chatDBServiceClient) AuthenticateUser(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, ChatDBService_AuthenticateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatDBServiceClient) RegisterUser(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, ChatDBService_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatDBServiceClient) IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueTokenResponse)
	err := c.cc.Invoke(ctx, ChatDBService_IssueToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatDBServiceClient) VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyTokenResponse)
	err := c.cc.Invoke(ctx, ChatDBService_VerifyToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatDBServiceClient) SetSessionState(ctx context.Context, in *SessionStateRequest, opts ...grpc.CallOption) (*SessionStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionStateResponse)
	err := c.cc.Invoke(ctx, ChatDBService_SetSessionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatDBServiceClient) PublishChat(ctx context.Context, in *ChatPublishRequest, opts ...grpc.CallOption) (*ChatPublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatPublishResponse)
	err := c.cc.Invoke(ctx, ChatDBService_PublishChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatDBServiceClient) GetChatHistory(ctx context.Context, in *ChatHistoryRequest, opts ...grpc.CallOption) (*ChatHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatHistoryResponse)
	err := c.cc.Invoke(ctx, ChatDBService_GetChatHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatDBServiceServer is the server API for ChatDBService service.
// All implementations must embed UnimplementedChatDBServiceServer
// for forward compatibility.
//
// --- gRPC DB 서비스 정의 ---
type ChatDBServiceServer interface {
	AuthenticateUser(context.Context, *AuthRequest) (*AuthResponse, error)
	RegisterUser(context.Context, *RegisterRequest) (*RegisterResponse, error)
	IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error)
	VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error)
	SetSessionState(context.Context, *SessionStateRequest) (*SessionStateResponse, error)
	PublishChat(context.Context, *ChatPublishRequest) (*ChatPublishResponse, error)
	GetChatHistory(context.Context, *ChatHistoryRequest) (*ChatHistoryResponse, error)
	mustEmbedUnimplementedChatDBServiceServer()
}

// UnimplementedChatDBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatDBServiceServer struct{}

func (UnimplementedChatDBServiceServer) AuthenticateUser(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthenticateUser not implemented")
}
func (UnimplementedChatDBServiceServer) RegisterUser(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedChatDBServiceServer) IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueToken not implemented")
}
func (UnimplementedChatDBServiceServer) VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedChatDBServiceServer) SetSessionState(context.Context, *SessionStateRequest) (*SessionStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSessionState not implemented")
}
func (UnimplementedChatDBServiceServer) PublishChat(context.Context, *ChatPublishRequest) (*ChatPublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishChat not implemented")
}
func (UnimplementedChatDBServiceServer) GetChatHistory(context.Context, *ChatHistoryRequest) (*ChatHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatHistory not implemented")
}
func (UnimplementedChatDBServiceServer) mustEmbedUnimplementedChatDBServiceServer() {}
func (UnimplementedChatDBServiceServer) testEmbeddedByValue()                       {}

// UnsafeChatDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatDBServiceServer will
// result in compilation errors.
type UnsafeChatDBServiceServer interface {
	mustEmbedUnimplementedChatDBServiceServer()
}

func RegisterChatDBServiceServer(s grpc.ServiceRegistrar, srv ChatDBServiceServer) {
	// If the following call panics, it indicates UnimplementedChatDBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatDBService_ServiceDesc, srv)
}

func _ChatDBService_AuthenticateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatDBServiceServer).AuthenticateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatDBService_AuthenticateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatDBServiceServer).AuthenticateUser(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatDBService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatDBServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatDBService_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatDBServiceServer).RegisterUser(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatDBService_IssueToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatDBServiceServer).IssueToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatDBService_IssueToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatDBServiceServer).IssueToken(ctx, req.(*IssueTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatDBService_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatDBServiceServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatDBService_VerifyToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatDBServiceServer).VerifyToken(ctx, req.(*VerifyTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatDBService_SetSessionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatDBServiceServer).SetSessionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatDBService_SetSessionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatDBServiceServer).SetSessionState(ctx, req.(*SessionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatDBService_PublishChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatPublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatDBServiceServer).PublishChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatDBService_PublishChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatDBServiceServer).PublishChat(ctx, req.(*ChatPublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatDBService_GetChatHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatDBServiceServer).GetChatHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatDBService_GetChatHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatDBServiceServer).GetChatHistory(ctx, req.(*ChatHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatDBService_ServiceDesc is the grpc.ServiceDesc for ChatDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatdb.ChatDBService",
	HandlerType: (*ChatDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthenticateUser",
			Handler:    _ChatDBService_AuthenticateUser_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _ChatDBService_RegisterUser_Handler,
		},
		{
			MethodName: "IssueToken",
			Handler:    _ChatDBService_IssueToken_Handler,
		},
		{
			MethodName: "VerifyToken",
			Handler:    _ChatDBService_VerifyToken_Handler,
		},
		{
			MethodName: "SetSessionState",
			Handler:    _ChatDBService_SetSessionState_Handler,
		},
		{
			MethodName: "PublishChat",
			Handler:    _ChatDBService_PublishChat_Handler,
		},
		{
			MethodName: "GetChatHistory",
			Handler:    _ChatDBService_GetChatHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat_db.proto",
}
